#include <argp.h>
#include <arpa/inet.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <time.h>
#include <unistd.h>

#include <bpf/libbpf.h>
#include <bpf/bpf.h>
#include "pingpong_kern.skel.h" // Generated by bpftool gen skeleton

// Define the same event structure as in the BPF program
struct event
{
    __u64 timestamp_ns;
    __u32 pid;
    __u16 sport;
    __u16 dport;
    // Add other fields as needed
};

static int handle_event(void *ctx, void *data, size_t data_sz)
{
    const struct event *e = data;
    // Process the event, e.g., print it or write to a file
    printf("ts: %llu, pid: %u, sport: %u, dport: %u\n",
           e->timestamp_ns, e->pid, ntohs(e->sport), ntohs(e->dport));
    return 0;
}

static volatile bool exiting = false;

static void sig_handler(int sig)
{
    exiting = true;
}

int main(int argc, char **argv)
{
    struct pingpong_kern_bpf *skel;
    struct ring_buffer *rb = NULL;
    int err;

    // Open, load, and verify BPF application
    skel = pingpong_kern_bpf__open_and_load();
    if (!skel)
    {
        fprintf(stderr, "Failed to open and load BPF skeleton\n");
        return 1;
    }

    // Attach tracepoints or kprobes
    err = pingpong_kern_bpf__attach(skel);
    if (err)
    {
        fprintf(stderr, "Failed to attach BPF skeleton\n");
        goto cleanup;
    }

    // Set up ring buffer polling
    rb = ring_buffer__new(bpf_map__fd(skel->maps.events), handle_event, NULL, NULL);
    if (!rb)
    {
        err = -1;
        fprintf(stderr, "Failed to create ring buffer\n");
        goto cleanup;
    }

    signal(SIGINT, sig_handler);
    signal(SIGTERM, sig_handler);

    printf("Successfully started! Please run `sudo cat /sys/kernel/debug/tracing/trace_pipe` "
           "to see output of the BPF programs.\n");

    while (!exiting)
    {
        err = ring_buffer__poll(rb, 100 /* timeout, ms */);
        // Ctrl-C will cause -EINTR
        if (err == -EINTR)
        {
            err = 0;
            break;
        }
        if (err < 0)
        {
            printf("Error polling ring buffer: %d\n", err);
            break;
        }
    }

cleanup:
    ring_buffer__free(rb);
    pingpong_kern_bpf__destroy(skel);
    return -err;
}
